language: elm
# elm: 0.19.0-bugfix6
# elm-test: 0.19.0-rev6
branches:
  only:
    - develop
script:
  - echo "Deploy"
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: "travis-ci-f841a"
  on:
    branch: develop