language: elm
# elm: 0.19.0-bugfix6
# elm-test: 0.19.0-rev6
branches:
  only:
    - develop
script:
  - cd app
  - elm-format --validate src/ && elm-test
after_success:
  - cd -
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: develop