language: elm
elm: 0.19.0-bugfix6
elm-test: 0.19.0-rev6
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy
#  - npm i -g firebase-ci
#  - firebase-ci deploy
branches:
  only:
    - develop
script:
  - echo "Deploy"
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT